### ISSUE TITLE
Advantages and Correllations to other languages

### ISSUE THREAD

**Issue by ClashLuke** [blenderfreaky/TempleLang#2]
Greetings good sir.\
I've just read through your code and saw that you labeled your language as [C--](https://www.cs.tufts.edu/~nr/c--/extern/man2.pdf) implying that it is more lightweight than C/++. Is that actually the case? Will everyone soon abandon their memory-safe rust, performant C and easy-to-use nim in favour of c--?

**Comment by thomaskilian** [comment]
Nope. It's just a school project to show how a compiler works.

**Comment by kilyanni** [comment]
Communicating over discord: Small brain
Communicating over GitHub Issues: Big brain

**Comment by thomaskilian** [comment]
.
